name: Chromatic

on:
    push
    # push:
    #     branches:
    #         - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.PAT_TOKEN }}
                  fetch-depth: 0

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: corepack enable
            - run: corepack prepare pnpm@9.13.0 --activate
            - run: pnpm install

            - uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.PAT_TOKEN }}
